version: "3"
services:
  linux:
    container_name: "mediasoup-video-conference"
    # image: "ubuntu"
    build: .
    restart: "always"
    tty: true
    ports:
      - "3000:3000"
      - "40000-40200:40000-40200"
    volumes:
      - "./:/home/node/src"
